apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgBDpbY84IkYoA+XxXr/5eI8J80mg/K0G0b4g9qkB3FmsGb09PqQWWg9hCTDsP2lQ0pXIED4o1JKXs3UKwsXWFMoYEylCE9I4OGh2odBT2CpFAv0bLMUIbx4PDetc9Eqhzq1PzaJIAObkXOUHi9s/faR8K31oRqthUZ1uVVfgj5PtwBodno8Nduc43DbCIlQtYg4JR/7Uv2eET+jurVBGyXS5m+Y6j2gaLxqJVXuuamex6H40FGvkbaHMmlnLwuk/VegFnqhPIxijX2IwqttZ4VRCKpA485C9/jyFlcCCxTGTLZ2Wv7JCkChbL636uk1fahSRqmKI/EAc5uPrb1DlPzTFnFeIsbGjstkG7Xl/0c3g6go4380eg3EUBQpdRK1MINrfcG+rYiBpRaCNlh/keWxgWfTZ8N5Z2bJej0OY4B1IvjIyu9/4jBbxmqfvurB9uQT0+HcX0i63jWIFEoaJWT99dbpYMgmG70O13xglIxhcLOrtEhg+Y5tP/u+bDBh2USs1tfhzOE4GuqL8Mqln8S8kxC1u99pvMRcfhnUJaEOojDwz1fSw/t+c6g3CR4SfuwTOMXToVlIEcCu+N9KqRLFLgI26+wse+ZrG2hjgdvEzvmBaH5D9rBzomI1EuvhvhO5Buss2bws0GafdpsV0wi8B8F3z2QeeqTzK04AFF4jXMkFkXz9AGLNlFBv3o4tBlE0Ac/4RLBefXn04vWqFdHnGX4MsATp8kgiMq+lS0XCvHMtV4tuk+6/MRoiHZRyXGRKrxiiTCGfQe/vROcyLczHZLK2RBDfBBal7xBxYXZSuBL/yZERBoc1IzsNCmbcqsclMqWlIxz26dxIKo4ltzWFvziHvH8lIaoHPqDO3NMTAQti6eSfn+h77zVUPx/PEX+6TST+uZg=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson
status: {}

