apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgCnBli1Ylts78PJIFw6v4B9hRCV+XSUNlTt/vxmRjUG+s2LBB4mfa7wWF9IAeVm7wJC+MYRedJg8GY+eCxa7kGupWo8hPgnHfvPkXGixVLJJkAqsG9Kpc7PZKysvbQ7ItB3DbvcPjSQFrfPHDKsrqi5J+1Iswj9a59Y32FYAaxvCnNBOeMYWTeAKhXlgTOMeTazNPYv06Bx0xBLD737/p3UpiBuh1BDVLVPk4TXYJ231uolIjkjVBhoWk2a75M+cyG3RJIxoI+UZghnp6CcgL82CZMIug82VNZPQbukwgpNEP0xmbniI4RpHNXXctUwa6zLiXqFwWB2UPbmixQOuJ5ZpgRWbyK7rns8HZL/cGCcm1x4sOgGrwPEjwBaRJnq3U84TSk04PuDzxqYpaRyOZ7SIyInjpspcwViQSU4CW+7Vv+CT+xFCv6htZL8LZftfzIsqCldG6A0xXnanS066P4yJzC+CtKx4CQDQXzXuBtygiVHsHjLNfZ/5zu+b6DUxb/3pzwnDluesf8Pma6GI3UzvJSq7FciMUp15ZMHNZKE6htBwatp3qgIziPSA6R5lFuzJhWD1QChczR0PO9yNlRBfK9H76C4shkASNm3j7jaWneOyTOedu4WG7irJs+iWF+EYniSmC9AdmTXozj2tknJoXVDA1AIy2G4hGqcCB9hXX7ZP5bvK1OiVjM6stfbBjghZUFpL6w57uJrlwBwhX1fzkZRjZsRt/vXMdQ3rJ6TljRk7nZG1W4k
  template:
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque
status: {}

