apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgAm+Gg4I1VcibWYRQ9bTLfj/IcHlTb41Ez1BDlC3cHiXEAQmHIlcqjuEl3bYzxNpHzdst4QKKaEbR94q4pApV1jXYv8DNKygyXq78sVfoTz4sSN+MVa6S0//9h/9GV3m0I3u9tk7uvXdnHUTQUEe3H1NrFUyKSVLhMl33GWb2EDb0NsiACiZQB8Jb/85ud5vZDqg5pPZLy/m4fdhLiHF0jShcz6vr4J+idsxQUcR/atn+v0atjaUJ4RzfrRJFroPL9avAqtUrDDsssYVtYf/+m9Wr5Vo+S1KbqX0iXJQ8FXxL6g3IdB+7lqyYJNpvJc25dWAAQxD1dlRguuA2rFrJFOvUQbvAWrbKklUcN9Im++Rb0ZEwsBuHD7pqT1kHppSTR2l5T+wzV5CHMgLbQ6toyxLdyihNZvCC5s7ixltSY3L13rzwdhesUbGas2FybQ+6jTzLHf5Gi7GUbp0g+U9sCgapBqTae4Oeq+QzMCcI4yi7ETZtl9vzSTV59N3plDUX+YsN5qXTtJKRy3+4S4a9PAmYdo+SpFdMO5dXj2mFWwqLQJJlToWCdGMtNtVvfdi6t6JXKMWWYmBByOiRPSHmJ+uQ+L+cHiBVLwuy0UDarqReqQH7gobHmpXoOVVOyhBRtWSg7ulLZZBoc+DxINpS6HRJf72QHNNz7VEwzqbFtE2qPZ5ZTPCsNLbJ8Ml21IAV1rLV5SSA4zN5yGryOw/OINJcRqtmcPly+elJ0+RsJOERQXN5GJsUz4
  template:
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque
status: {}

