apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgBQZZRiD4qHU0FVHLkKvhtpd1yhIFbcOFrtwJ6tL7sHaMeN2AX471y2lCSYUMMPse9eYP+SqAx15wAajQZi+gU/JDZ6Kju0HPgQ5Q5k9FvT5rK/dnmmFiF1BKG3/g6qvAhINyh3VN1l5XGu/NUYZDah4tFsYXvjBnxZbi6Ma148JE1Ayyh4v+ULdaUQdlyrngg8iBuJG4xA57OFap4H7Iq9/7rjXP7nrnLq2jfo3IVqoen8aVBOr+kju/ZxtqvH5u+i6WNBFgjJpxqsBWdCMhNYH/ShvxawDTHM4kKduS8Z6qqTK42DAfdvs5u0NB5MvL3GNaRWwy++pTiuLcVmYTjTOtMxgdxB7St65W0yBb9pdQN2WZQZ/SpYswjAu/pCGXq+TIo8FSk4PlgrO/b5bWhYLEmwbx3qKGgpjrVDPV0NKS/MLbMyQoFkJRarTTQCNfs2op51wFAgDzGKsrk37TB63uPqRNXMOBYwAB5heYn+rHI/Pn8ugkCAwTJEfeAkNSMosJ9dOMJy7DD8Gs9gVGnrW65GmrGD8TsjjSSCRvuZxWpb1F2+U0CcUtOyiknlt+7a0huutvzboEVkdk+KQJRzXOkayiic81Rp08INplhT5gDV9FtqS1sNiE5EiQqTuz/HEmcDknmgzwurx8v7e3pH5D1RSA8WzBdrLXO846AgA6n+x3DK405W5PXBc3Nf4ItjPzYYVurLOSZ0+lYDD9omoIsImUBLUgpwe1P8QxzJv+7T8hr7b70B
  template:
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque
status: {}

